#
# @file CLU_GENERALSETTINGS.yml
# @author Infotainment Software Development Team
#
# Copyright (c) 2025  Hyundai Motor Company,
# All Rights Reserved.
#
# Use and copying of this software and preparation of derivative works
# based upon this software are permitted. Any copy of this software or
# of any derivative work must include the above copyright notice, this
# paragraph and the one after it. Any distribution of this software or
# derivative works must comply with all applicable laws.
#
# This software is made available AS IS, and COPYRIGHT OWNERS DISCLAIMS
# ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE, AND NOTWITHSTANDING ANY OTHER PROVISION CONTAINED HEREIN, ANY
# LIABILITY FOR DAMAGES RESULTING FROM THE SOFTWARE OR ITS USE IS
# EXPRESSLY DISCLAIMED, WHETHER ARISING IN CONTRACT, TORT (INCLUDING
# NEGLIGENCE) OR STRICT LIABILITY, EVEN IF COPYRIGHT OWNERS ARE ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGES.
#

- CLU_GENERALSETTINGS:
  sfcVersion: "2.0.0"
  description: "Reference : [AV141] CLU_GENERALSETTINGS. Recommend: VALUE_CHANGED. Application Write, SFC Read"
  subscriptions:
    - ignElapseOn0msChanged:
      inputType: VALUE_CHANGED
      duration:
      values:
        - SFC.Private.IGNElapsed.ElapsedOn0ms: mElapsedOn0ms
  outputs:
      # Style is Theme_Name
    - SFC.Extension.CLU_GENERALSETTINGS.Inter_ThemeInfoFromAVNT:
      description: "Theme Info From AVNT<br>
                    Spec:CLU_GENERALSETTINGS[AV141]-Inter_ThemeInfoFromAVNT<br>
                    Published in CLU_GENERALSETTINGS[AV141]<br>
                    Subscribed in Screen_Control_Logic_2_0[CD121]"
      dataType: HString
      # 0x0: NONE, 0x1: KOREA, 0x2: ENGLISH_US, 0x3: ENGLISH_UK, 0x4: SIMPLIFIED_CHINESE, 0x5: TRADITIONAL_CHINESE, 0x6: FRENCH_EU, 0x7: SPANISH_EU, 0x8: ARABIC, 0x9: CZECH, 0xA: DANISH, 0xB: GERMAN, 0xC: ITALIAN, 0xD: DUTCH, 0xE: POLISH, 0xF: PORTUGUESE, 0x10: RUSSIAN, 0x11: SLOVAK, 0x12: SWEDISH, 0x13: TURKISH, 0x14: FRENCH_US, 0x15: SPANISH_US, 0x16: ENGLISH_INDIA, 0x17: NORWEGIAN, 0x18: FINNISH, 0x19: INDONESIAN, 0x1A: BRAZILIAN_PORTUGUESE, 0x1B: MALAY, 0x1C: HUNGARIAN, 0x1D: ENGLISH_AUSTRALIA, 0x1E: JAPANESE, 0x1F: HINDI, 0x20: HEBREW, 0x21: GREEK, 0x22: UKRAINIAN, 0x23: SLOVENIAN, 0x24: BULGARIAN, 0x25: CROATIAN, 0x26: ROMANIAN, 0x27: BENGALI, 0x28: MARATHI, 0x29: TELUGU, 0x2A: TAMIL, 0x2B: GUJARATI, 0x2C: KANNADA, 0x2D: ODIA, 0x2E: MALAYALAM, 0x2F: PUNJABI, 0x30: THAI, 0x31: LITHUANIAN, 0x32: LATVIAN, 0x33: ESTONIAN, 0x34: SIGNATURE_NULL, 0x35: MAX
    - SFC.Extension.CLU_GENERALSETTINGS.Inter_GeneralSettingsLanguageType:
      description: "General Settings Language Type<br>
                    Spec:CLU_GENERALSETTINGS[AV141]-Inter_GeneralSettingsLanguageType<br>
                    Published in CLU_GENERALSETTINGS[AV141]"
      dataType: HUInt64
      valueEnum:
        NONE: 0x0
        KOREA: 0x1
        ENGLISH_US: 0x2
        ENGLISH_UK: 0x3
        SIMPLIFIED_CHINESE: 0x4
        TRADITIONAL_CHINESE: 0x5
        FRENCH_EU: 0x6
        SPANISH_EU: 0x7
        ARABIC: 0x8
        CZECH: 0x9
        DANISH: 0xA
        GERMAN: 0xB
        ITALIAN: 0xC
        DUTCH: 0xD
        POLISH: 0xE
        PORTUGUESE: 0xF
        RUSSIAN: 0x10
        SLOVAK: 0x11
        SWEDISH: 0x12
        TURKISH: 0x13
        FRENCH_US: 0x14
        SPANISH_US: 0x15
        ENGLISH_INDIA: 0x16
        NORWEGIAN: 0x17
        FINNISH: 0x18
        INDONESIAN: 0x19
        BRAZILIAN_PORTUGUESE: 0x1A
        MALAY: 0x1B
        HUNGARIAN: 0x1C
        ENGLISH_AUSTRALIA: 0x1D
        JAPANESE: 0x1E
        HINDI: 0x1F
        HEBREW: 0x20
        GREEK: 0x21
        UKRAINIAN: 0x22
        SLOVENIAN: 0x23
        BULGARIAN: 0x24
        CROATIAN: 0x25
        ROMANIAN: 0x26
        BENGALI: 0x27
        MARATHI: 0x28
        TELUGU: 0x29
        TAMIL: 0x2A
        GUJARATI: 0x2B
        KANNADA: 0x2C
        ODIA: 0x2D
        MALAYALAM: 0x2E
        PUNJABI: 0x2F
        THAI: 0x30
        LITHUANIAN: 0x31
        LATVIAN: 0x32
        ESTONIAN: 0x33
        SIGNATURE_NULL: 0x34
        MAX: 0x35
      # 0x0: NONE, 0x1: KOREAN, 0x2: US_ENGLISH, 0x3: UK_ENGLISH, 0x4: CHINESE, 0x5: TAIWAN, 0x6: EU_FRENCH, 0x7: EU_SPANISH, 0x8: ARABIC, 0x9: CZECH, 0xA: DANISH, 0xB: GERMAN, 0xC: ITALIAN, 0xD: DUTCH, 0xE: POLISH, 0xF: EU_PORTUGUESE, 0x10: RUSSIAN, 0x11: SLOVAK, 0x12: SWEDISH, 0x13: TURKISH, 0x14: CA_FRENCH, 0x15: AM_SPANISH, 0x16: INDIA_ENGLISH, 0x17: NORWEGIAN, 0x18: FINNISH, 0x19: INDONESIA, 0x1A: BRA_PORTUGUESE, 0x1B: MALAY, 0x1C: HUNGARIAN, 0x1D: AU_ENGLISH, 0x1E: JAPANESE, 0x1F: HINDI, 0x20: HEBREW, 0x21: GREEK, 0x22: UKRAINIAN, 0x23: SLOVENE, 0x24: BULGARIAN, 0x25: CROATIAN, 0x26: RUMANIAN, 0x27: BENGALI, 0x28: MARATHI, 0x29: TELUGU, 0x2A: TAMIL, 0x2B: GUJARATI, 0x2C: KANNADA, 0x2D: ODIA, 0x2E: MALAYALAM, 0x2F: PUNJABI, 0x30: THAI, 0x31: SIGNATURE_NULL, 0x32: MAX
    - SFC.Extension.CLU_GENERALSETTINGS.Inter_GeneralSettingsDefaultLanguageType:
      description: "General Settings Default Language Type<br>
                    Spec:CLU_GENERALSETTINGS[AV141]-Inter_GeneralSettingsDefaultLanguageType<br>
                    Published in CLU_GENERALSETTINGS[AV141]"
      dataType: HUInt64
      valueEnum:
        NONE: 0x0
        KOREAN: 0x1
        US_ENGLISH: 0x2
        UK_ENGLISH: 0x3
        CHINESE: 0x4
        TAIWAN: 0x5
        EU_FRENCH: 0x6
        EU_SPANISH: 0x7
        ARABIC: 0x8
        CZECH: 0x9
        DANISH: 0xA
        GERMAN: 0xB
        ITALIAN: 0xC
        DUTCH: 0xD
        POLISH: 0xE
        EU_PORTUGUESE: 0xF
        RUSSIAN: 0x10
        SLOVAK: 0x11
        SWEDISH: 0x12
        TURKISH: 0x13
        CA_FRENCH: 0x14
        AM_SPANISH: 0x15
        INDIA_ENGLISH: 0x16
        NORWEGIAN: 0x17
        FINNISH: 0x18
        INDONESIA: 0x19
        BRA_PORTUGUESE: 0x1A
        MALAY: 0x1B
        HUNGARIAN: 0x1C
        AU_ENGLISH: 0x1D
        JAPANESE: 0x1E
        HINDI: 0x1F
        HEBREW: 0x20
        GREEK: 0x21
        UKRAINIAN: 0x22
        SLOVENE: 0x23
        BULGARIAN: 0x24
        CROATIAN: 0x25
        RUMANIAN: 0x26
        BENGALI: 0x27
        MARATHI: 0x28
        TELUGU: 0x29
        TAMIL: 0x2A
        GUJARATI: 0x2B
        KANNADA: 0x2C
        ODIA: 0x2D
        MALAYALAM: 0x2E
        PUNJABI: 0x2F
        THAI: 0x30
        SIGNATURE_NULL: 0x31
        MAX: 0x32
      # 0x0: NONE, 0x1: KILOMETER, 0x2: MILE, 0x3: SIGNATURE_NULL, 0x4: MAX
    - SFC.Extension.CLU_GENERALSETTINGS.Inter_GeneralSettingsDistanceUnit:
      description: "General Settings Distance Unit<br>
                    Spec:CLU_GENERALSETTINGS[AV141]-Inter_GeneralSettingsDistanceUnit<br>
                    Published in CLU_GENERALSETTINGS[AV141]"
      dataType: HUInt64
      valueEnum:
        NONE: 0x0
        KILOMETER: 0x1
        MILE: 0x2
        SIGNATURE_NULL: 0x3
        MAX: 0x4
      # 0x0: NONE, 0x1: HOUR_24, 0x2: HOUR_12, 0x3: SIGNATURE_NULL, 0x4: MAX
    - SFC.Extension.CLU_GENERALSETTINGS.Inter_GeneralSettingsTimeFormat:
      description: "General Settings Time Format<br>
                    Spec:CLU_GENERALSETTINGS[AV141]-Inter_GeneralSettingsTimeFormat<br>
                    Published in CLU_GENERALSETTINGS[AV141]"
      dataType: HUInt64
      valueEnum:
        NONE: 0x0
        HOUR_24: 0x1
        HOUR_12: 0x2
        SIGNATURE_NULL: 0x3
        MAX: 0x4
      # 0x0: NONE, 0x1: XLARGE, 0x2: LARGE, 0x3: MEDIUM, 0x4: SMALL, 0x5: SIGNATURE_NULL, 0x6: MAX
    - SFC.Extension.CLU_GENERALSETTINGS.Inter_GeneralSettingsFontSize:
      description: "General Settings Font Size<br>
                    Spec:CLU_GENERALSETTINGS[AV141]-Inter_GeneralSettingsFontSize<br>
                    Published in CLU_GENERALSETTINGS[AV141]"
      dataType: HUInt64
      valueEnum:
        NONE: 0x0
        XLARGE: 0x1
        LARGE: 0x2
        MEDIUM: 0x3
        SMALL: 0x4
        SIGNATURE_NULL: 0x5
        MAX: 0x6
