#ifndef COMMON_ENUM_H
#define COMMON_ENUM_H


#include "CommonDefine.h"


#if defined(PLATFORM_TARGET)
#define SCREEN_POSITION_X 0
#define SCREEN_POSITION_Y 0
#else
#define SCREEN_POSITION_X 50
#define SCREEN_POSITION_Y 100
#endif

#define SCREEN_SIZE_WIDTH 1280
#define SCREEN_SIZE_HEIGHT 720

#define SCREEN_MINIMUM_SIZE_WIDTH 640
#define SCREEN_MINIMUM_SIZE_HEIGHT 480
#define SCREEN_MAXIMUM_SIZE_WIDTH 2100
#define SCREEN_MAXIMUM_SIZE_HEIGHT 1300

#endif  // COMMON_ENUM_H
