@startuml

skinparam defaultFontName "Noto Sans CJK KR"
actor User order 10
participant FileSystem order 20
participant TestCase order 30
participant GenerateCaseData order 40
participant ExcelDataManager order 50
participant SignalDataManager order 60
participant PythonScript order 70
participant CaseDataWriter order 80

== 시작: TC 생성 요청 ==

User -> TestCase : click generate botton
TestCase -> GenerateCaseData : excuteGenerateCaseData()

== TC 생성 로직 ==

GenerateCaseData -> ExcelDataManager : 시트/TC 정보 요청
ExcelDataManager --> GenerateCaseData : 시트/TC 정보 반환\n(Sheet / TCName / Result / Case 별 정보)

loop 각 Sheet / TCName / Result / Case
    GenerateCaseData -> SignalDataManager : Signal 조건 정보 요청
    SignalDataManager --> GenerateCaseData : Signal 조건 정보 반환
    GenerateCaseData -> PythonScript : callPython() - Signal 정보 전달 및 조합 생성
    PythonScript --> GenerateCaseData : JSON 반환 - 생성된 조합

    GenerateCaseData -> GenerateCaseData : 1. AppendCase 처리
    GenerateCaseData -> GenerateCaseData : 2. OtherCase 처리
    GenerateCaseData -> GenerateCaseData : 3. Positive/Negative 분기 처리
    GenerateCaseData -> GenerateCaseData : 4. Positive&Negative Case Filtering Logic
    GenerateCaseData -> GenerateCaseData : 5. 유효 조합 수 이외 TC 제거 처리
    GenerateCaseData -> GenerateCaseData : 6. Precondition Case Extension 처리
    GenerateCaseData -> GenerateCaseData : 7. Config Signal Detection and Check Config True
end

== JSON File Save ==

GenerateCaseData -> CaseDataWriter : Send Generated TC Data - genTestCaseFile(mAllCaseJson, count)
GenerateCaseData -> FileSystem : Save JSON

@enduml