@startuml

actor User order 10

participant TestCase order 20
participant GenerateCaseData order 30
participant ExcelUtil order 50
participant "mAllCaseJson" as QJsonObject order 60


== Precondition Case Extension ==

User -> TestCase : 요청 - Generate TestCase

activate TestCase
TestCase -> GenerateCaseData : excuteGenerateCaseData()
deactivate TestCase

activate GenerateCaseData

GenerateCaseData -> ExcelUtil : isDescriptionPreconditionCount()
ExcelUtil --> GenerateCaseData : return maxPreconditionCnt
loop for each TCName/Result/Case
    GenerateCaseData -> QJsonObject : get list of TC combinations for Case
    QJsonObject --> GenerateCaseData : return list of TC combinations
    GenerateCaseData -> QJsonObject : get not-trigger precondition list for Case
    QJsonObject --> GenerateCaseData : return not-trigger precondition list

    alt not-trigger precondition list 크기 > 0
        GenerateCaseData -> GenerateCaseData : setPreconditionValues()
        activate GenerateCaseData
        GenerateCaseData -> GenerateCaseData : applyPrecondition()
        note right of GenerateCaseData
            not-trigger precondition list 크기만큼 list of TC combinations 의 각 case를 확장
        end note
        GenerateCaseData -> GenerateCaseData : Replace original Cases JSON with new extended Cases JSON
        deactivate GenerateCaseData
    else not-trigger precondition list 크기 <= 0
        GenerateCaseData -> GenerateCaseData : skip precondition handling
    end
end

deactivate GenerateCaseData

@enduml